name: tinycolor2
description: Flutter Color manipulation and conversion, ported from JS tinycolor2
version: 3.0.1
homepage: https://github.com/TinyCommunity/tinycolor2

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pigment: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.10.0

flutter:
